name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: TaskDb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: yourpassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Install dotnet-ef (Entity Framework CLI)
        run: dotnet tool install --global dotnet-ef
        
      - name: Restore dependencies
        run: dotnet restore

      - name: Build the application
        run: dotnet build --no-restore --configuration Release

      - name: Debug - List Files
        run: ls -R ${{ github.workspace }}


      - name: Run Migrations
        env:
          ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=TaskDb;Username=postgres;Password=yourpassword"
        run: dotnet ef database update --project ${{ github.workspace }}/Backend/Infrastructure/Infrastructure.csproj --startup-project ${{ github.workspace }}/Backend/Presentation/Presentation.csproj

      #- name: Run Unit Tests
       # run: dotnet test --no-restore --verbosity normal

      - name: Publish Application
        run: dotnet publish -c Release -o publish

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: publish
